FROM microsoft/iis
MAINTAINER Andrew Wu, https://www.facebook.com/andrewwu.blog.0928
LABEL Description="Course Of Microservice Demo" Vendor="Andrew Studio" Version="1.0.2016.1215"

# enable feature: ASP.NET 4.5
RUN dism /online /enable-feature /all /featurename:IIS-ASPNET45

# copy demoweb
ADD webapp c:/inetpub/wwwroot/

CMD [ "ping", "localhost", "-t" ]
